version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    restart: always
  camagru:
    container_name: camagru_container
    build: .
    image: camagru_image
    env_file: .env
    volumes:
      - /var/www/View/public/pictures #Enables persistance of saved images after restarting the server
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres
